{"level": "ERROR", "timestamp": "2024-08-02 17:45:07", "message": "An error occurred while retrieving metrics for UE ue1: [Errno 2] No such file or directory: 'C:\\\\Users\\\\snatanzi\\\\Desktop\\\\vs-code\\\\5G_RAN_SIM\\\\5G_RAN_SIM\\\\5G_RAN_SIM\\\\Config_files\\\\Config_files\\\\gNodeB_config.json'", "test_id": "abea0a2f-10a2-4149-9681-bb301aaf63f1"}
{"level": "ERROR", "timestamp": "2024-08-02 17:45:07", "message": "Exception traceback: Traceback (most recent call last):\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\API_Gateway\\API.py\", line 110, in ue_metrics\n    ue_manager = UEManager.get_instance(base_dir)  # Pass the base_dir argument\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 45, in get_instance\n    cls._instance = UEManager(base_dir)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 33, in __init__\n    self.config = Config(base_dir)\n                  ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\Config_files\\config.py\", line 7, in __init__\n    self.gNodeBs_config = self.load_json_config('gNodeB_config.json')\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\Config_files\\config.py\", line 16, in load_json_config\n    with open(file_path, 'r') as file:\n         ^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\snatanzi\\\\Desktop\\\\vs-code\\\\5G_RAN_SIM\\\\5G_RAN_SIM\\\\5G_RAN_SIM\\\\Config_files\\\\Config_files\\\\gNodeB_config.json'\n", "test_id": "abea0a2f-10a2-4149-9681-bb301aaf63f1"}
{"level": "INFO", "timestamp": "2024-08-02 17:45:07", "message": "UE IDs to be returned: ['ue1', 'ue2', 'ue3', 'ue4', 'ue5']", "test_id": "abea0a2f-10a2-4149-9681-bb301aaf63f1"}
{"level": "WARNING", "timestamp": "2024-08-02 18:10:24", "message": "UE UE1 not found in the system", "test_id": "3faea5a8-ce95-4de7-99a8-34efb92b68b0"}
{"level": "WARNING", "timestamp": "2024-08-02 18:17:38", "message": "UE UE1 not found in the system", "test_id": "2fc4b56a-3045-4153-99ca-7017cac674b9"}
{"level": "ERROR", "timestamp": "2024-08-02 18:24:13", "message": "An error occurred while retrieving metrics for UE ue1: type object 'UE' has no attribute 'ues'", "test_id": "a3010a87-4351-4c76-ac7b-f52bb40d90ae"}
{"level": "ERROR", "timestamp": "2024-08-02 18:24:13", "message": "Exception traceback: Traceback (most recent call last):\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\API_Gateway\\API.py\", line 113, in ue_metrics\n    if not ue_manager.get_ue_by_id(ue_id):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 112, in get_ue_by_id\n    ue = UE.get_ue_instance_by_id(ue_id_str)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue.py\", line 145, in get_ue_instance_by_id\n    for stored_ue_id, ue_instance in cls.ues.items():  # Use the correct attribute 'ues'\n                                     ^^^^^^^\nAttributeError: type object 'UE' has no attribute 'ues'\n", "test_id": "a3010a87-4351-4c76-ac7b-f52bb40d90ae"}
{"level": "ERROR", "timestamp": "2024-08-02 18:35:32", "message": "An error occurred while retrieving metrics for UE ue1: UEManager.get_instance() missing 1 required positional argument: 'base_dir'", "test_id": "b9a41867-8fa5-49f8-9445-c3d7d5cc61d0"}
{"level": "ERROR", "timestamp": "2024-08-02 18:35:32", "message": "Exception traceback: Traceback (most recent call last):\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\API_Gateway\\API.py\", line 113, in ue_metrics\n    if not ue_manager.get_ue_by_id(ue_id):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 112, in get_ue_by_id\n    ue = UE.get_ue_instance_by_id(ue_id_str)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue.py\", line 145, in get_ue_instance_by_id\n    ue_manager = UEManager.get_instance()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: UEManager.get_instance() missing 1 required positional argument: 'base_dir'\n", "test_id": "b9a41867-8fa5-49f8-9445-c3d7d5cc61d0"}
{"level": "ERROR", "timestamp": "2024-08-02 18:38:37", "message": "An error occurred while retrieving metrics for UE ue1: UEManager.get_instance() missing 1 required positional argument: 'base_dir'", "test_id": "9d934717-11cd-4278-826d-6ec0c0644be6"}
{"level": "ERROR", "timestamp": "2024-08-02 18:38:37", "message": "Exception traceback: Traceback (most recent call last):\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\API_Gateway\\API.py\", line 108, in ue_metrics\n    if not ue_manager.get_ue_by_id(ue_id):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 112, in get_ue_by_id\n    ue = UE.get_ue_instance_by_id(ue_id_str)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue.py\", line 145, in get_ue_instance_by_id\n    ue_manager = UEManager.get_instance()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: UEManager.get_instance() missing 1 required positional argument: 'base_dir'\n", "test_id": "9d934717-11cd-4278-826d-6ec0c0644be6"}
{"level": "ERROR", "timestamp": "2024-08-02 18:52:28", "message": "An error occurred while retrieving metrics for UE ue1: UEManager.get_instance() missing 1 required positional argument: 'base_dir'", "test_id": "45eefb77-3a7b-40af-9978-ef2b9ac43202"}
{"level": "ERROR", "timestamp": "2024-08-02 18:52:28", "message": "Exception traceback: Traceback (most recent call last):\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\API_Gateway\\API.py\", line 108, in ue_metrics\n    if not ue_manager.get_ue_by_id(ue_id):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 112, in get_ue_by_id\n    ue = UE.get_ue_instance_by_id(ue_id_str)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue.py\", line 145, in get_ue_instance_by_id\n    ue_manager = UEManager.get_instance()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: UEManager.get_instance() missing 1 required positional argument: 'base_dir'\n", "test_id": "45eefb77-3a7b-40af-9978-ef2b9ac43202"}
{"level": "INFO", "timestamp": "2024-08-02 19:22:07", "message": "UE IDs to be returned: ['ue1', 'ue2', 'ue3', 'ue4', 'ue5']", "test_id": "0d624838-a7c6-44ab-94bf-57fe0b1b371a"}
{"level": "ERROR", "timestamp": "2024-08-02 19:22:07", "message": "An error occurred while retrieving metrics for UE ue1: UEManager.get_instance() missing 1 required positional argument: 'base_dir'", "test_id": "0d624838-a7c6-44ab-94bf-57fe0b1b371a"}
{"level": "ERROR", "timestamp": "2024-08-02 19:22:07", "message": "Exception traceback: Traceback (most recent call last):\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\API_Gateway\\API.py\", line 108, in ue_metrics\n    if not ue_manager.get_ue_by_id(ue_id):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 112, in get_ue_by_id\n    ue = UE.get_ue_instance_by_id(ue_id_str)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue.py\", line 145, in get_ue_instance_by_id\n    ue_manager = UEManager.get_instance()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: UEManager.get_instance() missing 1 required positional argument: 'base_dir'\n", "test_id": "0d624838-a7c6-44ab-94bf-57fe0b1b371a"}
{"level": "ERROR", "timestamp": "2024-08-02 19:48:01", "message": "An error occurred while retrieving metrics for UE ue1: UEManager.get_instance() missing 1 required positional argument: 'base_dir'", "test_id": "6a539891-ac9d-440b-b6da-3d389dc1d1ad"}
{"level": "ERROR", "timestamp": "2024-08-02 19:48:01", "message": "Exception traceback: Traceback (most recent call last):\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\API_Gateway\\API.py\", line 106, in ue_metrics\n    if not ue_manager.get_ue_by_id(ue_id):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 112, in get_ue_by_id\n    ue = UE.get_ue_instance_by_id(ue_id_str)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue.py\", line 145, in get_ue_instance_by_id\n    ue_manager = UEManager.get_instance()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: UEManager.get_instance() missing 1 required positional argument: 'base_dir'\n", "test_id": "6a539891-ac9d-440b-b6da-3d389dc1d1ad"}
